import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# Function to read the CSV file and load the data into a Pandas DataFrame
def load_csv_to_dataframe(csv_file):
    return pd.read_csv(csv_file)


# Function to plot KDE for each model separately, for a given descriptor
def plot_kde_by_model(dataframe, descriptor_name):
    models = dataframe['model'].unique()  # Get all unique models
    plt.figure(figsize=(10, 6))

    # Loop over each model and plot the KDE for that model's descriptor data
    for model in models:
        model_data = dataframe[dataframe['model'] == model][descriptor_name]
        sns.kdeplot(model_data, label=model, lw=2)

    plt.title(f"KDE for {descriptor_name} Descriptor (Per Model)")
    plt.xlabel('Value')
    plt.ylabel('Density')
    plt.legend(title="Model")
    plt.grid(True)
    plt.show()


# Function to generate plots for all descriptors by model
def plot_all_descriptors_by_model(csv_file):
    df = load_csv_to_dataframe(csv_file)

    # List of descriptors to plot
    descriptors = ['A3', 'D1', 'D2', 'D3', 'D4']

    # Plot each descriptor with separate lines for each model
    for descriptor in descriptors:
        plot_kde_by_model(df, descriptor)


if __name__ == "__main__":
    csv_file = 'shape_descriptors.csv'  # The CSV file generated by the first script
    plot_all_descriptors_by_model(csv_file)
